### ISSUE TITLE
Building the examples

### ISSUE THREAD

**Issue by pachiras** [PapenfussLab/bionix#17]
Hello,

I was so impressed by your paper. This approach seems promising!
By the way, when I cloned the repository and tried to build example from the `examples` directory,
`nix` gave me an error saying:
```
~/workspace/bionix/examples (master=) $ nix build
error: file 'bionix' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/pachiras/workspace/bionix/examples/default.nix:3:18
```
I'm new to nix system. Could you tell me how to solve this?

**Comment by jbedo** [comment]
Hi!

The error message arises because Nix doesn't know where bionix is. Adding the flag `-I bionix=../` or `-I bionix=/home/pachiras/workspace/bionix` should resolve the problem.

**Comment by pachiras** [comment]
Thank you for your fast reply. It worked!
From now, I'll start learning nix & bionix :smiley:

**Comment by jbedo** [comment]
No worries! There's not a great depth of documentation yet, so if you need help with anything just send me an email or open an issue.
