### ISSUE TITLE
Samtools faidx query region functionality

### ISSUE THREAD

**Issue by lezhou8** [PapenfussLab/bionix#22]
Hi,
Currently `bionix.samtools.faidx` has the functionality of indexing a fasta file, but samtools-faidx also has the functionality of querying a region of a fasta file. Perhaps another tool can be made for that purpose, maybe called samtools-queryRegion.

**Comment by lezhou8** [comment]
It would be similar to the existing `bionix.samtools.faidx` but perhaps line 19 would be something like this:
`samtools faidx ${optionalString (flags != null) flags} input.fasta > $out`, since samtools faidx outputs the region query to stdout, hence the redirection.

There would also have to be a way for regions to be specified as inputs. E.g.
```
{ bionix
, flags ? null
, regions ? ""
}:
```

**Comment by jbedo** [comment]
Regions should probably be a list not a string.

**Comment by lezhou8** [comment]
In that case, this could be a way for regions to be specified:
```
{ bionix
, flags ? null
, regions ? []
}:
```
and line 19 could be modified to something like this:
```
samtools faidx ${optionalString (flags != null) flags} input.fasta ${concatStringsSep " " regions} > $out
```
